name: Deploy to Server

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env: # эти переменные будут доступны для docker compose
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_ROOT_PASSWORD: ${{ secrets.DATABASE_ROOT_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ragu
          chmod 600 ~/.ssh/id_ragu
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Copy docker-compose.prod.yml to server
        run: |
          scp -i ~/.ssh/id_ragu ./docker-compose.prod.yml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/docker-compose.prod.yml

      - name: Generate ragu.env on server
        run: |
          ssh -i ~/.ssh/id_ragu ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          cat > ~/ragu.env <<'EOF'
          DATABASE_NAME=${{ secrets.DATABASE_NAME }}
          DATABASE_USER=${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
          DATABASE_ROOT_PASSWORD=${{ secrets.DATABASE_ROOT_PASSWORD }}
          EOF
              "
      - name: Deploy Docker Compose to server
        run: |
          ssh -i ~/.ssh/id_ragu ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} bash -s <<'EOF'
            # Создаём env файл
            cat > ~/ragu.env <<EOL
          DATABASE_NAME=${{ secrets.DATABASE_NAME }}
          DATABASE_USER=root
          DATABASE_PASSWORD=${{ secrets.DATABASE_ROOT_PASSWORD }}
          DATABASE_ROOT_PASSWORD=${{ secrets.DATABASE_ROOT_PASSWORD }}
          EOL

            # Логин в GHCR
            echo '${{ secrets.GHCR_TOKEN }}' | docker login ghcr.io -u '${{ secrets.GHCR_USERNAME }}' --password-stdin

            # Запуск MySQL контейнера (чтобы root с % появился)
            docker compose -p ragu --env-file ~/ragu.env -f ~/docker-compose.prod.yml up -d database

            # Ждём, пока MySQL станет доступен
            until docker exec ragu-database-1 mysqladmin ping -h "localhost" --silent; do
              echo "Waiting for database..."
              sleep 5
            done

            # Создаём root пользователя с доступом с любого хоста
            docker exec -i ragu-database-1 mysql -uroot -p"${DATABASE_ROOT_PASSWORD}" <<SQL
          CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY '${DATABASE_ROOT_PASSWORD}';
          GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
          FLUSH PRIVILEGES;
          SQL

            # Запуск остальных контейнеров
            docker compose -p ragu --env-file ~/ragu.env -f ~/docker-compose.prod.yml up -d
          EOF
